### PR TITLE
Update board.js

### PR DESCRIPTION
**Pull request by liviez**
API url changed to agile path

### CODE REVIEW

**Comment by Sebon1980** [comment]
HI! I updated the same in my pullrequest.... but nice to see im not the only one who use this ;-))

**Comment by floralvikings** [comment]
Sorry about taking so long to get to these everyone; been an extremely busy couple of months and this library has fallen behind a bit in my priority list.  I'll try to get a look at all the open issues/pull requests this weekend and publish a new release.

**Comment by liviez** [comment]
Hi, I have been using this module quite heavily lately. It would be nice to have the promise version of it. 

For now, I wrapped it up in my code but either you could have a look at this or I will send you a pull request as soon as I have time. 

It should just be to change the makeRequest function to check if you have a callback as a second argument or not and if not return a promise instead. Or a major breaking change to use only request-promise instead. I would rather go for supporting both versions.

**Comment by floralvikings** [comment]
@liviez Promise support should have been added in release 2.6.0: see #55, it was released and published to npm in version [2.6.0](https://github.com/floralvikings/jira-connector/releases/tag/v2.6.0).

**Comment by kylefarris** [comment]
Fixes #69

**Pull request merged**
