### PR TITLE
Add & apply linting

### PR DESCRIPTION
**Pull request by G-Rath**
🎉

I'm not a contribue on the repo, so can't setup any pipelines or actions, but here you go!

I used my standard configuration with minimal changes so you can see what it's like.

In particular, it does mean it's using 2 spaces instead of 4. I've also committed the `package-lock.json`, as that's good practice.

Happy to discuss and explain anything if you've got questions, or want to request changes :)

I am interested in knowing what language level is being targeted, as it looks to be pre-ES6, but if we're happy w/ ES6+ we can clean up quite a bit w/ template strings & default properties 🤷‍♀ 

----

Also: I deprecated `path_prefix` in the config, since it was easily done. Everything seems to typically be in camelCase; for now I've added the other nested snake_case properties to the ignore list of the eslint rule, and will circle back once things have stabilized to deprecate them.

### CODE REVIEW

**Comment by G-Rath** [comment]
I've chucked on `checkJs` too, w/ `// @ts-nocheck` now on every js file, as the majority of api files are looking pretty decent, w/ no funky weird errors - it's just general JSDoc improvements, so I think it'll be worth it.

`// @ts-nocheck` means we can incrementally fix up each js file at a time :D

Also, I found a `let` in `JiraClient`, so I guess we're ES6 🎉

**Comment by MrRefactoring** [comment]
This is a really huge PR. It takes me a while to think and analyze what we can do. I am afraid that we cannot switch to es6 so easily

**Comment by G-Rath** [comment]
@MrRefactoring Completely understandable; just so we're clear:

* I've not used any ES6 features,
* I've made no logical code changes in the `api/` classes - the majority of the diff is just applying prettier
* You're actually already using ES6: https://github.com/floralvikings/jira-connector/blob/4aba3421a1524c683c0e30d504527c07ae007f99/index.js#L383
* The only logical code change I did was here: https://github.com/floralvikings/jira-connector/pull/208/files#diff-168726dbe96b3ce427e7fedce31bb0bcR169-R175 (and is backwards compatible - happy to revert if you'd like 🙂)

**Comment by MrRefactoring** [comment]
Oh my

It seems you're right)

Added 3 years ago

**Comment by G-Rath** [comment]
I just realised, promises are ES6 too :joy:

**Pull request closed without merging**
