### PR TITLE
Added Full Property Retrieval to Search

### PR DESCRIPTION
**Pull request by kylefarris**
Atlassian recently (and finally!!) added the ability to get full property definitions on searches. This will allow us to get them!

### CODE REVIEW

**Comment by floralvikings** [comment]
@kylefarris You mind fixing the merge conflicts here?  Planning on doing a release either this or next weekend, and I'd like to have this captured along with #54 and #55

**Comment by kylefarris** [comment]
Hey man, sorry for the super late conflict resolution (was so easy to fix). Anyways, got it done.

Thanks!

**Comment by kylefarris** [comment]
Hey! This would be a super easy merge. Would you mind merging it or making me an official collaborator? I might be able to help clear up some of these issues and PRs in the queue.

Thanks!

**Comment by floralvikings** [comment]
@kylefarris Hey there, sorry about taking, just, an unacceptable amount of time to get back to you; as you can probably tell from the lack of updates, I haven't really had much time to maintain this repository lately.  Life and whatnot.

I'll (try to) get to all of the outstanding PR's and issues this weekend, and if you're still interested in being an official collaborator we can definitely discuss that.

**Comment by floralvikings** [comment]
@kylefarris And just like that I let another two weeks go by without being able to review PR's.  I've sent you a collaborator invite 😄 

Let me know if you'd like me to publish a new release to npm and I can increment the version number and do so

**Comment by kylefarris** [comment]
It's all good man. We're all busy and that's not a bad thing! FWIW, you can actually add me as an "owner" for this package on NPM as well. Makes it so the publishing to NPM doesn't have to go through you all the time.

**Pull request merged**
