### PR TITLE
Fixed broken URL for auth API

### PR DESCRIPTION
**Pull request by MrRefactoring**
Fixes for #135

### CODE REVIEW

**Comment by floralvikings** [comment]
@MrRefactoring Thank you so much for all the excellent contributions! Sorry I haven't seen to them sooner, I have very little time to spend with this repository any more.  Would you like to have commit rights to this repository so that you can continue to make improvements without having to wait for me?

**Comment by MrRefactoring** [comment]
Yes, I would like to continue developing this library. It would also be good to get any access to npm.

Since at the moment, there is a critical error

**Comment by floralvikings** [comment]
@MrRefactoring I've sent a GitHub collaborator invite; is your npm handle also `@MrRefactoring`?

**Comment by MrRefactoring** [comment]
Right

**Comment by floralvikings** [comment]
@MrRefactoring done!  I've just published all of the PR's that were merged today.

**Pull request merged**
